### ISSUE TITLE
package.json dependency not found

### ISSUE THREAD

**Issue by titanobulls** [sustainlabs/slabs-cms-website#8]
give last dependencies here pls

**Comment by molmen** [comment]
"devDependencies": {
    "browser-sync": "^2.24.4",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^5.0.0",
    "gulp-clean-css": "^3.9.4",
    "gulp-concat": "^2.6.1",
    "gulp-notify": "^3.2.0",
    "gulp-rename": "^1.2.3",
    "gulp-rsync": "0.0.8",
    "gulp-sass": "^4.0.1",
    "gulp-uglify": "^3.0.0",
    "gulp-util": "^3.0.8"
  }
